version: '3'
services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ./variables.env
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
 
  node-service:
    build: ./api
    restart: always
    env_file:
      - ./variables.env
    depends_on:
      - db
    # ports:
    #   - "3000:3000"
    scale: 3
 
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - node-service
    ports:
      - "8080:80"
 
volumes:
  db_data: